### ISSUE TITLE
bug in +DSS_MATLAB/APIUtil.m 

### ISSUE THREAD

**Issue by ironman127** [dss-extensions/dss_matlab#17]
The matlab function on line 152(get_int32_gr_array) have a bug.  The calling on function setdatatype(data, 'int32Ptr', 1, cnt) is wrong.
It should be setdatatype(data, 'int32Ptr', 1, cnt(1)) , missing a index on argument cnt.

**Comment by PMeira** [comment]
Indeed, thanks for pointing that. It seems the only `setdatatype` called with incorrect arguments. I'll push the change and prepare new packages. 

Some other issues related to the engine should be fixed in the next few weeks, pending the final DSS C-API 0.14.0 release.

**Comment by PMeira** [comment]
Premade packages available at: https://github.com/dss-extensions/dss_matlab/releases/tag/0.13.4-2
