### ISSUE TITLE
callib call errors due to  missing library argument

### ISSUE THREAD

**Issue by Hell3000** [dss-extensions/dss_matlab#20]
I had an error using the monitor interface. I think at these places (might be more, I didn't regexp-search) the first argument of the library `obj.libname` has to be added. It worked in my case. 

![Unbenannt](https://github.com/user-attachments/assets/38d55fc3-0bb1-4563-a0e6-abe3f4859cf0)

By the way: 

Great Work! Thank you and  everyone involved for creating and maintaining this great interface !

**Comment by PMeira** [comment]
Thanks for reporting! Preparing a new release with a fix now.

**Comment by PMeira** [comment]
Done in https://github.com/dss-extensions/dss_matlab/releases/tag/0.14.3-1
